### ISSUE TITLE
Regex search breaks completely after selecting a specific mod

### ISSUE THREAD

**Issue by CrazylikE** [veiset/poe-vendor-string#11] opened 2022-05-28 21:22 UTC
I choose the following mods under "I don't want any of these mods":

1. Players cannot Regenerate Life, Mana or Energy Shield
2. -X% maximum Player Resistances
    Players have X% less Recovery Rate of Life and Energy Shield
3. Players have X% reduced effect of Non-Curse Auras from Skills
4. Players have X% reduced Chance to Block Players have X% less Armour

This makes my regex the following: "!ss r|m p|ege|non|loc"
This works, now only the maps with none of the above mods are highlighted.

Then when I add the following:

5. Monsters gain X% of Maximum Life as Extra Maximum Energy Shield

My regex becomes: "!ss r|m p|ege|non|loc|m l"

When I paste that into the in-game tab search, nothing gets highlighted.

**Comment by veiset** [comment] 2022-05-29 13:49
Thanks for the report. 😁 I found the cause of the bug. The issue was that `m l` matched `item level`. 

The issue should be fixed and the fix is live on the webpage. Let me know if you find any other issues!

**Closed by veiset** 2022-05-29 13:49 UTC
