### ISSUE TITLE
Flask regex needs tweaking

### ISSUE THREAD

**Issue by Meisen1977** [veiset/poe-vendor-string#75] opened 2023-06-16 21:39 UTC
Specifically "+(32-35) to Maximum Charges". This is the prefix "Ample", and is shortened to "mpl".

For whatever weird reason this highlights ALL Basalt, Stibnite and Sulphur flasks, no matter what rolls they have.

(I doubt this is relevant, but just in case; all flasks checked were magic, had 20% quality and were ilvl 84)

**Comment by veiset** [comment] 2023-06-20 11:35
Wow, thats weird. Thanks for the report!

I found the issue. The issue is that if you copy the text of flasks (with extended mods) some of the flasks have `Implicit modifier` which gets matched by `mpl`. For example an aquamarine flask has the text, with advanced copy:

```
Requirements:
Level: 44
--------
Item Level: 85
--------
{ Implicit Modifier }
Creates Chilled Ground on Use (implicit)
(You are Chilled while standing in Chilled Ground) (implicit)
```

This should be fixed and live in like 5 minutes.

**Closed by veiset** 2023-06-20 11:35 UTC
